### ISSUE TITLE
🐛 [BUG] CUDA error when computing Wigner D matrix on gpu.

### ISSUE THREAD

**Issue by floatingCatty** [e3nn/e3nn#423]
**Describe the bug**
The method 03.D_from_angles does not work if I put all angles to cuda devices, it suggest that some variables in the computation are located in CPU.

**To Reproduce**
Just call o3.D_from_angles(cuda_alpha, cuda_beta, cuda_gamma), or the same using wigner_D(l, a, b, y) ...

**Expected behavior**
support computation of Wigner D matrix on cuda.

**Comment by arhanjain** [comment]
+1

**Comment by mitkotak** [comment]
Sorry for that ! If it's not too much of hassle can you paste the trace. My suspicion is that its because of [this](https://github.com/e3nn/e3nn/blob/f95297952303347a8a3cfe971efe449c710c43b2/e3nn/o3/_irreps.py#L146-L147)

**Comment by arhanjain** [comment]
i got around it by sending the tensor generated in the function to the device of the inputs

```python
def wigner_D(l: int, alpha: torch.Tensor, beta: torch.Tensor, gamma: torch.Tensor) -> torch.Tensor:
    r"""Wigner D matrix representation of :math:`SO(3)`.

    It satisfies the following properties:

    * :math:`D(\text{identity rotation}) = \text{identity matrix}`
    * :math:`D(R_1 \circ R_2) = D(R_1) \circ D(R_2)`
    * :math:`D(R^{-1}) = D(R)^{-1} = D(R)^T`
    * :math:`D(\text{rotation around Y axis})` has some property that allows us to use FFT in `ToS2Grid`

    Parameters
    ----------
    l : int
        :math:`l`

    alpha : `torch.Tensor`
        tensor of shape :math:`(...)`
        Rotation :math:`\alpha` around Y axis, applied third.

    beta : `torch.Tensor`
        tensor of shape :math:`(...)`
        Rotation :math:`\beta` around X axis, applied second.

    gamma : `torch.Tensor`
        tensor of shape :math:`(...)`
        Rotation :math:`\gamma` around Y axis, applied first.

    Returns
    -------
    `torch.Tensor`
        tensor :math:`D^l(\alpha, \beta, \gamma)` of shape :math:`(2l+1, 2l+1)`
    """
    alpha, beta, gamma = torch.broadcast_tensors(alpha, beta, gamma)
    alpha = alpha[..., None, None] % (2 * math.pi)
    beta = beta[..., None, None] % (2 * math.pi)
    gamma = gamma[..., None, None] % (2 * math.pi)
    #### SEE CHANGE HERE #####
    X = so3_generators(l).to(alpha.device)
    ##############################
    return torch.matrix_exp(alpha * X[1]) @ torch.matrix_exp(beta * X[0]) @ torch.matrix_exp(gamma * X[1])
```

**Comment by WinstonWinstonWinston** [comment]
+1 Still facing this issue. Fixed by using solution posted by Arhan Jain (arhanjain) on Jan 30.
